version: '3.8'

services:
  productos-service:
    build:
      context: productos-service
    container_name: productos-service
    ports:
      - "8080:8080"
    networks:
      - backend-net

  inventario-service:
    build:
      context: inventario-service
    container_name: inventario-service
    ports:
      - "8081:8081"
    networks:
      - backend-net
    depends_on:
      - productos-service

networks:
  backend-net:
    driver: bridge
